name: Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: '[{ "title": "Commit Message: "${{ github.event.head_commit.message }}"", "footer": {"text": "Author: ${{ github.event.commits[0].author.username }}"} }]'
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
