name: Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        #DISCORD_EMBEDS: '[{ "title": Commit Message ${{ toJSON(github.event.head_commit.message) }}", "footer": {"text": "Author: ${{ github.event.commits[0].author.username }}"} }]'
        DISCORD_EMBEDS: `[{ "title": "Commit Message", "footer": {"text": 'Author: ${{ github.event.commits[0].author.username }}'} }]`
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
