name: Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: testing ku 
      run: echo '${{ github.event.head_commit.message }}'

    - name: send to discord
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then export BRANCHENV=Production ; else export BRANCHENV=Staging; fi
        curl -X POST -H 'Content-Type: application/json' --url ${{ secrets.DISCORD_WEBHOOK }} --data '{"content":"The project ${{ github.repository }} has been deployed.","embeds":[{"title":"**Environment**\n'${BRANCHENV}'","description": "Commit Message '${{ toJSON(github.event.head_commit.message) }}' sip ok","footer":{"text":"Author: ${{ github.event.head_commit.author.name }} "} }]}'
        #curl -X POST -H 'Content-Type: application/json' --url ${{ secrets.DISCORD_WEBHOOK }} --data '{"content":"The project ${{ github.repository }} has been deployed.","embeds":[{"title": "Commit Message '${{ toJSON(github.event.head_commit.message) }}' sip ok","footer":{"text":"Author: ${{ github.event.commits[0].author.username }} "} }]}'
#    - name: Discord Notification
#      env:
#        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        #DISCORD_EMBEDS: "[{ 'title': 'Commit Message ', 'footer': {'text': 'Author ${{ github.event.commits[0].author.username }}'} }]"
#        DISCORD_EMBEDS: '[{ "title": "Commit Message '${{ toJSON(github.event.head_commit.message) }}'", "footer": {"text": "Author: ${{ github.event.commits[0].author.username }}"} }]'
#      uses: Ilshidur/action-discord@master
#      with:
#        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
