name: Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: testing ku 
      run: echo '${{ github.event.head_commit.message }}'

    - name: send to discord
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then export BRANCHENV=Production ; else export BRANCHENV=Staging; fi
        curl -X POST -H 'Content-Type: application/json' --url ${{ secrets.DISCORD_WEBHOOK }} --data '{"content":"The project ${{ github.repository }} has been deployed.","embeds":[{"description": "> ## Environment \n\n'${BRANCHENV}'\n\n> ## Commit Message \n '${{ toJSON(github.event.head_commit.message) }}'\n\n> ## Author**\n${{ github.event.head_commit.author.name }}" }]}'
        #curl -X POST -H 'Content-Type: application/json' --url ${{ secrets.DISCORD_WEBHOOK }} --data '{"content":"The project ${{ github.repository }} has been deployed.","embeds":[{"description": "**Environment**\n'${BRANCHENV}'\n\n**Commit Message** \n '${{ toJSON(github.event.head_commit.message) }}'\n\n**Author**\n${{ github.event.head_commit.author.name }}" }]}'
